[2024-08-10 16:07:52,487][flwr][INFO] - Starting Flower server, config: num_rounds=5, no round_timeout
[2024-08-10 16:07:52,520][flwr][INFO] - Flower ECE: gRPC server running (5 rounds), SSL is disabled
[2024-08-10 16:07:52,520][flwr][INFO] - [INIT]
[2024-08-10 16:07:52,520][flwr][INFO] - Using initial global parameters provided by strategy
[2024-08-10 16:07:52,520][flwr][INFO] - Evaluating initial global parameters
[2024-08-10 16:07:52,520][flwr][INFO] - 
[2024-08-10 16:07:52,520][flwr][INFO] - [ROUND 1]
[2024-08-10 16:08:04,715][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 5)
[2024-08-10 16:09:27,105][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-08-10 16:09:27,128][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-08-10 16:12:12,131][grpc._server][ERROR] - Exception iterating responses: 
Traceback (most recent call last):
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/flwr/server/superlink/fleet/grpc_bidi/flower_service_servicer.py", line 117, in Join
    ins_wrapper: InsWrapper = next(ins_wrapper_iterator)
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/flwr/server/superlink/fleet/grpc_bidi/grpc_bridge.py", line 165, in ins_wrapper_iterator
    self._raise_if_closed()
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/flwr/server/superlink/fleet/grpc_bidi/grpc_bridge.py", line 81, in _raise_if_closed
    raise GrpcBridgeClosed()
flwr.server.superlink.fleet.grpc_bidi.grpc_bridge.GrpcBridgeClosed
