[2024-07-27 14:58:37,524][flwr][INFO] - Starting Flower server, config: num_rounds=4, no round_timeout
[2024-07-27 14:58:37,555][flwr][INFO] - Flower ECE: gRPC server running (4 rounds), SSL is disabled
[2024-07-27 14:58:37,555][flwr][INFO] - [INIT]
[2024-07-27 14:58:37,555][flwr][INFO] - Using initial global parameters provided by strategy
[2024-07-27 14:58:37,555][flwr][INFO] - Evaluating initial global parameters
[2024-07-27 14:58:37,555][flwr][INFO] - 
[2024-07-27 14:58:37,555][flwr][INFO] - [ROUND 1]
[2024-07-27 14:58:44,083][flwr][INFO] - configure_fit: strategy sampled 2 clients (out of 2)
[2024-07-27 14:58:56,844][grpc._server][ERROR] - Exception iterating responses: 
Traceback (most recent call last):
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/grpc/_server.py", line 654, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/flwr/server/superlink/fleet/grpc_bidi/flower_service_servicer.py", line 117, in Join
    ins_wrapper: InsWrapper = next(ins_wrapper_iterator)
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/flwr/server/superlink/fleet/grpc_bidi/grpc_bridge.py", line 165, in ins_wrapper_iterator
    self._raise_if_closed()
  File "/Users/roccopiovardaro/Desktop/PythonProjects/Federated_Learning/.venv/lib/python3.9/site-packages/flwr/server/superlink/fleet/grpc_bidi/grpc_bridge.py", line 81, in _raise_if_closed
    raise GrpcBridgeClosed()
flwr.server.superlink.fleet.grpc_bidi.grpc_bridge.GrpcBridgeClosed
[2024-07-27 14:58:59,738][flwr][INFO] - aggregate_fit: received 1 results and 1 failures
[2024-07-27 14:58:59,759][flwr][WARNING] - No fit_metrics_aggregation_fn provided
